<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Movie;
use Carbon\Carbon;

class MovieSeeder extends Seeder
{
    public function run(): void
    {
        $currentTimestamp = Carbon::now();

        $movies = [
            ['title'=>'The Dark Knight','short_description'=>'Batman faces the Joker in Gotham City.','long_description'=>'Batman must confront the chaotic Joker who threatens Gotham. As the city descends into anarchy, he is forced to confront his own moral limits. The battle between order and chaos pushes everyone to the edge, testing loyalty, courage, and justice.','image'=>'thedarkknight.jpg','trailer_url'=>'https://www.youtube.com/embed/EXeTwQWrcwY','release_year'=>2008,'age_rating'=>'PG-13','runtime'=>'2h 32mins'],
            ['title'=>'Inception','short_description'=>'A thief steals secrets through dreams.','long_description'=>'Dom Cobb infiltrates people’s dreams to steal secrets. When tasked with planting an idea, he assembles a skilled team. The lines between reality and dreams blur, challenging his perception of truth and threatening his own psyche.','image'=>'inception.jpg','trailer_url'=>'https://www.youtube.com/embed/YoHD9XEInc0','release_year'=>2010,'age_rating'=>'PG-13','runtime'=>'2h 28mins'],
            ['title'=>'Parasite','short_description'=>'A poor family infiltrates a wealthy household.','long_description'=>'The Kim family cleverly integrates into the Park family’s home. Their scheme starts as harmless fun but soon spirals into dark consequences. Social tensions, jealousy, and desperation collide in a story that mixes comedy with tragedy.','image'=>'parasite.jpg','trailer_url'=>'https://www.youtube.com/embed/5xH0HfJHsaY','release_year'=>2019,'age_rating'=>'R','runtime'=>'2h 12mins'],
            ['title'=>'Interstellar','short_description'=>'Explorers travel through a wormhole to save humanity.','long_description'=>'Astronauts journey through space and time to find a habitable planet. Facing cosmic anomalies and personal sacrifices, they must push humanity’s limits. Every choice carries profound consequences for Earth and those they love.','image'=>'interstellar.jpg','trailer_url'=>'https://www.youtube.com/embed/zSWdZVtXT7E','release_year'=>2014,'age_rating'=>'PG-13','runtime'=>'2h 49mins'],
            ['title'=>'The Shawshank Redemption','short_description'=>'Two men find hope in prison.','long_description'=>'Andy and Red form a deep bond in Shawshank prison. Over decades, they endure corruption, injustice, and despair. Their story is a powerful exploration of hope, friendship, and resilience.','image'=>'theshawshankredemption.jpg','trailer_url'=>'https://www.youtube.com/embed/6hB3S9bIaco','release_year'=>1994,'age_rating'=>'R','runtime'=>'2h 22mins'],
            ['title'=>'Avengers: Endgame','short_description'=>'Heroes unite to undo Thanos’ devastation.','long_description'=>'After the catastrophic events of Infinity War, the Avengers regroup to undo the snap. They face challenges across time and space, making sacrifices that test their courage. The fate of the universe rests on their unity and determination.','image'=>'avengersendgame.jpg','trailer_url'=>'https://www.youtube.com/embed/TcMBFSGVi1c','release_year'=>2019,'age_rating'=>'PG-13','runtime'=>'3h 1min'],
            ['title'=>'The Matrix','short_description'=>'A hacker discovers reality is a simulation.','long_description'=>'Neo discovers the world he knows is a simulated reality controlled by machines. Guided by Morpheus, he embraces his destiny as The One. He must challenge both human and machine forces to liberate minds.','image'=>'thematrix.jpg','trailer_url'=>'https://www.youtube.com/embed/vKQi3bBA1y8','release_year'=>1999,'age_rating'=>'R','runtime'=>'2h 16mins'],
            ['title'=>'Gone Girl','short_description'=>'A man becomes the prime suspect in his wife’s disappearance.','long_description'=>'Nick faces scrutiny when his wife Amy vanishes. The media frenzy intensifies, and secrets are revealed. Dark twists and manipulations turn the investigation into a suspenseful and twisted narrative.','image'=>'gonegirl.jpg','trailer_url'=>'https://www.youtube.com/embed/2-_-1nJf8Vg','release_year'=>2014,'age_rating'=>'R','runtime'=>'2h 29mins'],
            ['title'=>'Arrival','short_description'=>'A linguist communicates with aliens.','long_description'=>'When mysterious spacecraft appear, linguist Louise Banks deciphers their language. The process reveals profound insights about time, memory, and choice. Humanity’s future may depend on understanding these enigmatic visitors.','image'=>'arrival.jpg','trailer_url'=>'https://www.youtube.com/embed/tFMo3UJ4B4g','release_year'=>2016,'age_rating'=>'PG-13','runtime'=>'1h 56mins'],
            ['title'=>'Forrest Gump','short_description'=>'A man witnesses historical events.','long_description'=>'From childhood hardships to extraordinary moments in history, Forrest Gump’s innocent perspective and perseverance shape his remarkable journey through life.','image'=>'forrestgump.jpg','trailer_url'=>'https://www.youtube.com/embed/bLvqoHBptjg','release_year'=>1994,'age_rating'=>'PG-13','runtime'=>'2h 22mins'],
            ['title'=>'Mad Max: Fury Road','short_description'=>'A woman rebels in a post-apocalyptic desert.','long_description'=>'In a barren desert, Furiosa helps Max rebel against a tyrannical warlord. They embark on a high-octane chase across wastelands. Survival, trust, and redemption drive every brutal encounter.','image'=>'madmax.jpg','trailer_url'=>'https://www.youtube.com/embed/hEJnMQG9ev8','release_year'=>2015,'age_rating'=>'R','runtime'=>'2h 0mins'],
            ['title'=>'John Wick','short_description'=>'An ex-hitman seeks vengeance.','long_description'=>'After gangsters kill his dog, John Wick emerges from retirement to exact revenge. His pursuit is relentless, precise, and violent. The underworld is shaken by his return, as loyalty and betrayal collide.','image'=>'johnwick.jpg','trailer_url'=>'https://www.youtube.com/embed/2AUmvWm5ZDQ','release_year'=>2014,'age_rating'=>'R','runtime'=>'1h 41mins'],
            ['title'=>'Blade Runner 2049','short_description'=>'A blade runner uncovers a dangerous secret.','long_description'=>'K, a blade runner, uncovers a secret that could destabilize society. He embarks on a journey to uncover the truth, questioning humanity, memory, and identity. Every step takes him closer to shocking revelations.','image'=>'bladerunner.jpg','trailer_url'=>'https://www.youtube.com/embed/gCcx85zbxz4','release_year'=>2017,'age_rating'=>'R','runtime'=>'2h 44mins'],
            ['title'=>'Dune','short_description'=>'A family fights for control of Arrakis.','long_description'=>'House Atreides becomes embroiled in a deadly conflict over Arrakis, the galaxy’s most valuable planet. Amid desert battles, betrayal, and prophecy, Paul Atreides rises to challenge his fate.','image'=>'dune.jpg','trailer_url'=>'https://www.youtube.com/embed/n9xhJrPXop4','release_year'=>2021,'age_rating'=>'PG-13','runtime'=>'2h 35mins'],
            ['title'=>'Se7en','short_description'=>'Detectives hunt a serial killer.','long_description'=>'Two detectives track a serial killer who uses the seven deadly sins as inspiration for his crimes. Each crime is meticulously planned to shock and disturb. Tension, suspense, and moral dilemmas escalate toward a devastating climax.','image'=>'se7en.jpg','trailer_url'=>'https://www.youtube.com/embed/znmZoVkCjpI','release_year'=>1995,'age_rating'=>'R','runtime'=>'2h 7mins'],
            ['title'=>'Shutter Island','short_description'=>'A marshal investigates a psychiatric facility.','long_description'=>'U.S. Marshal Teddy Daniels investigates the disappearance of a patient on Shutter Island. As he delves deeper, he uncovers secrets that challenge his sanity. The line between reality and delusion blurs in a tense psychological thriller.','image'=>'shutterisland.jpg','trailer_url'=>'https://www.youtube.com/embed/5iaYLCiq5RM','release_year'=>2010,'age_rating'=>'R','runtime'=>'2h 18mins'],
            ['title'=>'The Revenant','short_description'=>'A frontiersman fights for survival.','long_description'=>'Hugh Glass is mauled by a bear and left for dead, battling the brutal wilderness and human threats to survive.','image'=>'therevenant.jpg','trailer_url'=>'https://www.youtube.com/embed/lYQ-v9Y0L-s','release_year'=>2015,'age_rating'=>'R','runtime'=>'2h 36mins'],
            ['title'=>'Jurassic Park','short_description'=>'Dinosaurs escape the theme park.','long_description'=>'Cloned dinosaurs break free from Jurassic Park’s enclosures, creating chaos. Scientists and visitors must survive as nature’s power proves unpredictable.','image'=>'jurassicpark.jpg','trailer_url'=>'https://www.youtube.com/embed/_jKEqDKpJLw','release_year'=>1993,'age_rating'=>'PG-13','runtime'=>'2h 7mins'],
            ['title'=>'The Godfather','short_description'=>'The patriarch passes control of his empire.','long_description'=>'The aging Don Vito Corleone transfers control of the family crime empire to his reluctant son Michael. As Michael navigates loyalty, betrayal, and power, the family legacy hangs in the balance.','image'=>'thegodfather.jpg','trailer_url'=>'https://www.youtube.com/embed/sY1S34973zA','release_year'=>1972,'age_rating'=>'R','runtime'=>'2h 55mins'],
            ['title'=>'Fight Club','short_description'=>'Two men form an underground fight club.','long_description'=>'An insomniac office worker and a soap maker start an underground fight club that spirals into chaos. Identity, freedom, and destruction collide in unexpected ways.','image'=>'fightclub.jpg','trailer_url'=>'https://www.youtube.com/embed/SUXWAEX2jlg','release_year'=>1999,'age_rating'=>'R','runtime'=>'2h 19mins'],
            ['title'=>'Gladiator','short_description'=>'A betrayed general seeks revenge.','long_description'=>'Maximus, a Roman general, is betrayed and his family murdered. Sold into slavery, he rises as a gladiator, seeking vengeance against the corrupt emperor. His journey is filled with honor, courage, and epic battles.','image'=>'gladiator.jpg','trailer_url'=>'https://www.youtube.com/embed/owK1qxDselE','release_year'=>2000,'age_rating'=>'R','runtime'=>'2h 35mins'],
            ['title'=>'Titanic','short_description'=>'A tragic romance aboard the Titanic.','long_description'=>'Jack and Rose fall in love aboard the doomed Titanic. Their romance faces societal boundaries and the looming disaster of the ship’s sinking. Love, tragedy, and survival define their unforgettable journey.','image'=>'titanic.jpg','trailer_url'=>'https://www.youtube.com/embed/kVrqfYjkTdQ','release_year'=>1997,'age_rating'=>'PG-13','runtime'=>'3h 14mins'],
            ['title'=>'The Lion King','short_description'=>'A young lion rises to reclaim his kingdom.','long_description'=>'Simba must confront betrayal and tragedy to reclaim his place as king. Through loss, guidance, and courage, he learns responsibility, leadership, and the circle of life.','image'=>'thelionking.jpg','trailer_url'=>'https://www.youtube.com/embed/4sj1MT05lAA','release_year'=>1994,'age_rating'=>'G','runtime'=>'1h 28mins'],
            ['title'=>'Avatar','short_description'=>'A human integrates into an alien world.','long_description'=>'Jake Sully joins the Na’vi on Pandora to understand and protect their world. Facing conflict between humans and natives, he discovers identity, loyalty, and love.','image'=>'avatar.jpg','trailer_url'=>'https://www.youtube.com/embed/5PSNL1qE6VY','release_year'=>2009,'age_rating'=>'PG-13','runtime'=>'2h 42mins'],
            ['title'=>'The Silence of the Lambs','short_description'=>'An FBI agent consults a cannibalistic killer.','long_description'=>'Clarice Starling seeks the help of Hannibal Lecter to catch another serial killer. As she navigates psychological manipulation and danger, tension and suspense build. A chilling exploration of crime, intellect, and fear.','image'=>'thesilenceofthelambs.jpg','trailer_url'=>'https://www.youtube.com/embed/W6Mm8Sbe__o','release_year'=>1991,'age_rating'=>'R','runtime'=>'1h 58mins'],
            ['title'=>'The Prestige','short_description'=>'Rival magicians spiral into obsession.','long_description'=>'Two magicians engage in a bitter rivalry, attempting ever more dangerous tricks to outdo each other. Their obsession leads to deception, tragedy, and shocking revelations. Ambition and secrecy push them to extremes.','image'=>'theprestige.jpg','trailer_url'=>'https://www.youtube.com/embed/ijXiruUs-_M','release_year'=>2006,'age_rating'=>'PG-13','runtime'=>'2h 10mins'],
            ['title'=>'La La Land','short_description'=>'Love and dreams collide in Los Angeles.','long_description'=>'Mia and Sebastian pursue their dreams while navigating love. Joy, heartbreak, and ambition intertwine as they face choices that shape their future and artistry.','image'=>'lalaland.jpg','trailer_url'=>'https://www.youtube.com/embed/0pdqf4P9MB8','release_year'=>2016,'age_rating'=>'PG-13','runtime'=>'2h 8mins'],
            ['title'=>'The Social Network','short_description'=>'The creation of Facebook and its consequences.','long_description'=>'Mark Zuckerberg develops Facebook, facing friendship, betrayal, and legal battles. Innovation and ambition collide with ethical dilemmas, exploring power, intellect, and the cost of success in the digital age.','image'=>'thesocialnetwork.jpg','trailer_url'=>'https://www.youtube.com/embed/lB95KLmpLR4','release_year'=>2010,'age_rating'=>'PG-13','runtime'=>'2h 0mins'],
            ['title'=>'Coco','short_description'=>'A boy journeys to the Land of the Dead.','long_description'=>'Miguel explores the Land of the Dead to uncover his family’s history and pursue his passion for music. Along the way, he learns about memory, legacy, and the importance of family.','image'=>'coco.jpg','trailer_url'=>'https://www.youtube.com/embed/Rvr68u6k5sU','release_year'=>2017,'age_rating'=>'PG','runtime'=>'1h 45mins'],
            ['title'=>'Joker','short_description'=>'A man descends into madness.','long_description'=>'Arthur Fleck struggles with society’s indifference and personal hardships. His transformation into the Joker explores chaos, despair, and the darkness within.','image'=>'joker.jpg','trailer_url'=>'https://www.youtube.com/embed/zAGVQLHvwOY','release_year'=>2019,'age_rating'=>'R','runtime'=>'2h 2mins'],
            ['title'=>'Black Panther','short_description'=>'A king defends his nation and legacy.','long_description'=>'T’Challa returns to Wakanda to assume the throne and protect his people. Facing political intrigue and external threats, he learns the responsibilities of leadership, justice, and heritage.','image'=>'blackpanther.jpg','trailer_url'=>'https://www.youtube.com/embed/Q7Q3WbF__NY','release_year'=>2018,'age_rating'=>'PG-13','runtime'=>'2h 14mins'],
            ['title'=>'The Grand Budapest Hotel','short_description'=>'A concierge and lobby boy navigate chaos.','long_description'=>'Gustave H and Zero navigate theft, murder, and quirky adventures in a fictional European hotel. Humor, loyalty, and eccentricity define their journey.','image'=>'thegrandbudapesthotel.jpg','trailer_url'=>'https://www.youtube.com/embed/WNz9_f2q0fQ','release_year'=>2014,'age_rating'=>'R','runtime'=>'1h 39mins'],
            ['title'=>'Memento','short_description'=>'A man with short-term memory loss seeks justice.','long_description'=>'Leonard suffers from memory loss while trying to find his wife’s killer. Using notes and tattoos, he pieces together clues. A non-linear narrative explores memory, obsession, and truth.','image'=>'memento.jpg','trailer_url'=>'https://www.youtube.com/embed/Ih0wo_WtGxo','release_year'=>2000,'age_rating'=>'R','runtime'=>'1h 53mins'],
            ['title'=>'The Truman Show','short_description'=>'A man’s life is broadcast unknowingly.','long_description'=>'Truman Burbank discovers his seemingly ordinary life is a reality TV show. As he uncovers the truth, he confronts deception, control, and freedom. A thought-provoking tale of identity and reality.','image'=>'thetrumanshow.jpg','trailer_url'=>'https://www.youtube.com/embed/dlnmQbPGuls','release_year'=>1998,'age_rating'=>'PG','runtime'=>'1h 43mins'],
            ['title'=>'Whiplash','short_description'=>'A drummer faces a ruthless mentor.','long_description'=>'Andrew Neiman trains under a perfectionist music instructor, pushing his talent to extremes. Obsession, ambition, and personal sacrifice define a journey of music and intensity.','image'=>'whiplash.jpg','trailer_url'=>'https://www.youtube.com/embed/7d_jQycdQGo','release_year'=>2014,'age_rating'=>'R','runtime'=>'1h 47mins'],
        ];

        foreach ($movies as $movieData) {
            Movie::create(array_merge($movieData, [
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ]));
        }
    }
}
